- name: Provision Ansible Worker Container
  hosts: all
  connection: local
  become: true

  tasks:
  - name: Create ansible config folder
    file:
      path: /etc/ansible
      state: directory
      mode: 0755

  - name: Fetch Ansible.cfg
    get_url:
      url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
      dest: /etc/ansible/ansible.cfg

  - name: Enabled YAML output
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^stdout_callback=' 
      line: 'stdout_callback = yaml'

# Default password is currently set to jenkins
# you may want to consider changing this in the future.
  - name: Add the Jenkins user
    user:
      name: jenkins
      password: '$6$/tbuN4rpdJrGGRhL$cn1OWS7mwJUrx7ph7pBv8sWhGStZZnN1VC1gvnhFo3RQrvaWU2LwBI7XXENdYykJQwXuSDS1fIJgg1JkERnBC.'
      shell: /bin/sh
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      createhome: yes
      state: present
      home: /home/jenkins