- name: Provision Ansible Worker Container
  hosts: all
  connection: local
  become: true

  tasks:
  - name: Create ansible config folder
    file:
      path: /etc/ansible
      state: directory
      mode: 0755

  - name: Fetch Ansible.cfg
    get_url:
      url: https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg
      dest: /etc/ansible/ansible.cfg

  - name: Enabled YAML output
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^stdout_callback=' 
      line: 'stdout_callback = yaml'

  - name: Add the Jenkins user
    user:
      name: jenkins
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa

    # This password should probably be changed and encrypted.
  - name: Set the password for the jenkins user
    shell: echo "jenkins:jenkins" | chpasswd